version: '3.4'

services:
  blaster.webapi:
    build:
      context: .
      dockerfile: src/Blaster.WebApi/Dockerfile

  auth-proxy:
    build:
      context: .
      dockerfile: src/auth-proxy/Dockerfile