version: '3.4'

services:
  blaster.webapi:
    build:
      context: .
      dockerfile: src/Blaster.WebApi/Dockerfile
    networks:
      development:
        aliases:
          - blaster

  auth-proxy:
    build:
      context: .
      dockerfile: src/auth-proxy/Dockerfile
    networks:
      development:
        aliases:
          - auth-proxy

networks:
  development: