version: "3"

services:
  blaster:
    build: 
      context: ./
    ports:
      - "5000:80"
    depends_on:
      - header-injector-proxy
      - auth-proxy
      - capability-service
    environment: 
      - BLASTER_CAPABILITYSERVICE_API_URL=http://capability-service:3000
      - BLASTER_AWS_JANITOR_API_URL=http://aws-janitor:3000
  header-injector-proxy:
    build: 
      context: ./fake_dependencies/header-injector-proxy
    ports:
      - "5002:50802"
    depends_on:
      - auth-proxy
    environment:
      - FORWARD_ADDRESS=auth-proxy:50800
  auth-proxy:
    build: 
      context: ./src/auth-proxy
    ports:
      - "5001:50800"
    environment:
      - FORWARD_ADDRESS=blaster:80
  capability-service:
    build: 
      context: ./fake_dependencies/capability-service
    ports:
      - "50900:3000"
  aws-janitor:
    build: 
      context: ./fake_dependencies/aws-janitor
    ports:
      - "50901:3000"
  tika:
    build: 
      context: ./fake_dependencies/tika
    ports:
      - "50902:3000"