
swagger: "2.0"
info:
  version: 1.0.0
  title: Cognito sidecar API
basePath: /
paths:
  /system/health:
    get:
      tags:
      - "system"
      summary: Shallow healthcheck
      responses:
        200:
          description: OK
  /aws/console:
    get:
      tags:
      - "aws"
      summary: "Construct a link for AWS Console"
      parameters:
      - in: query
        name: idToken
        type: string
        description: The numbers of items to return
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/AWSConsoleLinkResponse"
definitions:
  AWSConsoleLinkResponse:
    type: "object"
    properties:
      absoluteUrl:
        type: "string"