swagger: "2.0"
info:
  version: 1.0.0
  title: Container Registry API
basePath: /api
consumes: 
  - "application/json"
produces:
  - "application/json"
paths:
  /repositories:
    get:
      summary: Returns list of available repositories
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/repository-list"
    post:
      summary: Creates a new repository
      parameters:
        - in: body
          name: body
          required: true
          description: Information describing the repository to create
          schema:
            $ref: "#/definitions/repository-input"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/repository"
          headers:
            location:
              type: string
              description: A URI to a location when the repository can be retrieved
  /repositories/{id}:
    get:
      summary: Returns an existing repository
      parameters:
        - in: path
          name: id
          required: true
          description: Id of the repository to return
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/repository"
        404:
          description: Not Found
definitions:
  repository-list:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/repository"
  repository:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      createdDate:
        type: string
  repository-input:
    type: object
    properties:
      name:
        type: string