apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blaster
  namespace: $(kubernetes-namespace)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blaster
  template:
    metadata:
      labels:
        app: blaster
    spec:
      containers:
      - name: container
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/blaster:$(Build.BuildId)
        ports:
        - containerPort: 80
          name: web
        env:
          - name:  blaster_message
            value: banana
          - name: blaster_apikey
            value: $(blaster_apikey)
          - name: BLASTER_DASHBOARD_SERVICE_URL
            value: http://dash
          - name: BLASTER_COGNITO_POOL_ID
            value: $(BLASTER_COGNITO_POOL_ID)
          - name: BLASTER_COGNITO_REGION
            value: $(BLASTER_COGNITO_REGION)
          - name: BLASTER_COGNITO_CLIENT_ID
            value: $(BLASTER_COGNITO_CLIENT_ID)
          - name: BLASTER_COGNITO_CLIENT_SECRET
            value: $(BLASTER_COGNITO_CLIENT_SECRET)
          - name: BLASTER_COGNITO_API_URL
            value: http://localhost:5000
      - name: container
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/cognito-api:$(Build.BuildId)
        ports:
        - containerPort: 5000
        # resources:
        #   requests:
        #     cpu: "20m"
        #     memory: "100M"
        #   limits:
        #     cpu: "20m"
        #     memory: "55M"