apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blaster
  namespace: $(kubernetes-namespace)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blaster
  template:
    metadata:
      labels:
        app: blaster
    spec:
      containers:
      - name: blaster
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/blaster:$(Build.BuildId)
        ports:
        - containerPort: 80
          name: web
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
          - name:  blaster_message
            value: banana
          - name: blaster_apikey
            value: $(blaster_apikey)
          - name: BLASTER_DASHBOARD_SERVICE_URL
            value: http://dash
          - name: BLASTER_COGNITO_POOL_ID
            value: $(BLASTER_COGNITO_POOL_ID)
          - name: BLASTER_COGNITO_REGION
            value: $(BLASTER_COGNITO_REGION)
          - name: BLASTER_COGNITO_CLIENT_ID
            value: $(BLASTER_COGNITO_CLIENT_ID)
          - name: BLASTER_COGNITO_CLIENT_SECRET
            value: $(BLASTER_COGNITO_CLIENT_SECRET)
          - name: BLASTER_COGNITO_API_URL
            value: http://localhost:5000
          - name: BLASTER_TEAMSERVICE_API_URL
            value: $(BLASTER_TEAMSERVICE_API_URL)
          - name: BLASTER_URL
            value: $(BLASTER_URL)
