apiVersion: v1
kind: Service
metadata:
  name: blaster
  namespace: $(kubernetes-namespace)
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: blaster
    project: selfservice
    department: devex
spec:
  ports:
    - name: external
      port: 80
      targetPort: web
  selector:
    app: blaster