apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: blaster
  name: blaster
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: blaster
    spec:
      containers:
      - env:
        - name: BLASTER_AWS_JANITOR_API_URL
          value: http://aws-janitor:3000
        - name: BLASTER_CAPABILITYSERVICE_API_URL
          value: http://capability-service:3000
        image: blaster
        name: blaster
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
